INSERT INTO FILM (TITLE, TYPE) VALUES ('Matrix 11', 'NEW');
INSERT INTO FILM (TITLE, TYPE) VALUES ('Spider Man', 'REGULAR');
INSERT INTO FILM (TITLE, TYPE) VALUES ('Spider Man 2', 'REGULAR');
INSERT INTO FILM (TITLE, TYPE) VALUES ('Out of Africa', 'OLD');
